-- MySQL Script generated by MySQL Workbench
-- Sun May 13 16:03:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contactos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Contactos` (
  `numero` INT NOT NULL,
  `nombreContacto` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grupos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Grupos` (
  `nombre` INT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Contactos_has_Grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contactos_has_Grupos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Contactos_has_Grupos` (
  `Contactos_numero` INT NOT NULL,
  `Grupos_nombre` INT NOT NULL,
  PRIMARY KEY (`Contactos_numero`, `Grupos_nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
